ARG ARCH=
FROM ${ARCH}python:3.9-slim-bullseye
RUN pip3 install --upgrade pip

# create app folder
RUN mkdir -p /todoFilesApp

# copy requirements file
COPY ./todoFilesApp/requirements.txt /todoFilesApp/requirements.txt

# set the working directory
WORKDIR /todoFilesApp

# install requirements from requirements file
#RUN pip3 install -r ./requirements.txt

# copy remaining app files
COPY ./todoFilesApp /todoFilesApp

# create group and user
RUN groupadd -r pyuser && useradd -g pyuser pyuser

# set ownership and permissions
RUN chown -R pyuser:pyuser /todoFilesApp

# switch to user pyuser
USER pyuser

# expose container port
EXPOSE 8081

# start application with specified user
ENTRYPOINT [ "python" ]
CMD [ "-u", "todoFilesApp.py" ] 