ARG ARCH=
FROM ${ARCH}python:3.9-slim-bullseye
RUN pip3 install --upgrade pip

# create app folder
RUN mkdir -p /todoApp

# copy requirements file
COPY ./todoApp/requirements.txt /todoApp/requirements.txt

# set the working directory
WORKDIR /todoApp

# install requirements from requirements file
#RUN pip3 install -r ./requirements.txt

# copy remaining app files
COPY ./todoApp /todoApp

# create group and user
RUN groupadd -r pyuser && useradd -g pyuser pyuser

# set ownership and permissions
RUN chown -R pyuser:pyuser /todoApp

# switch to user pyuser
USER pyuser

# expose container port
EXPOSE 8080

# start application with specified user
ENTRYPOINT [ "python" ]
CMD [ "-u", "todoApp.py" ] 